TOPICS = [
    "Language modeling",
    "Optimization",
    # "Deep learning",
    "Neural networks",
    "Reinforcement learning",
    "Probabilistic graphical models",
    "Machine translation",
    # "Time series",
    # "Object detection",
    # "Multi-agent systems",
    # "Bioinformatics in machine learning",
    "Machine learning in social media",
    "Image and video processing",
    "Speech recognition",
    # "Semantic analysis",
    # "Natural language understanding",
    # "Sentiment analysis",
    "Human-computer interaction",
    # "Pattern recognition",
    # "Robotics and automation",
    # "Big data analytics",
    # "Quantum computing in AI",
    # "Generative Adversarial Networks (GANs)",
    # "Transfer learning",
    # "AI ethics and social implications",
    # "AI in healthcare",
    # "Computer vision in autonomous vehicles",
    # "AI in cybersecurity",
    # "Actor-Critic Methods",
    "Information retrieval",
    "Linguistics",
]